// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WillowDBClient is the client API for WillowDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WillowDBClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
}

type willowDBClient struct {
	cc grpc.ClientConnInterface
}

func NewWillowDBClient(cc grpc.ClientConnInterface) WillowDBClient {
	return &willowDBClient{cc}
}

func (c *willowDBClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/willowdb.WillowDB/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WillowDBServer is the server API for WillowDB service.
// All implementations must embed UnimplementedWillowDBServer
// for forward compatibility
type WillowDBServer interface {
	Ping(context.Context, *empty.Empty) (*empty.Empty, error)
	mustEmbedUnimplementedWillowDBServer()
}

// UnimplementedWillowDBServer must be embedded to have forward compatible implementations.
type UnimplementedWillowDBServer struct {
}

func (UnimplementedWillowDBServer) Ping(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedWillowDBServer) mustEmbedUnimplementedWillowDBServer() {}

// UnsafeWillowDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WillowDBServer will
// result in compilation errors.
type UnsafeWillowDBServer interface {
	mustEmbedUnimplementedWillowDBServer()
}

func RegisterWillowDBServer(s grpc.ServiceRegistrar, srv WillowDBServer) {
	s.RegisterService(&WillowDB_ServiceDesc, srv)
}

func _WillowDB_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WillowDBServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/willowdb.WillowDB/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WillowDBServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WillowDB_ServiceDesc is the grpc.ServiceDesc for WillowDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WillowDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "willowdb.WillowDB",
	HandlerType: (*WillowDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _WillowDB_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "willowdb.proto",
}
